---
version: 2.1

orbs: 
  aws-cli: circleci/aws-cli@4.1.2
  ansible-playbook: orbss/ansible-playbook@0.0.5
  ruby: circleci/ruby@2.1.1

jobs:
  provisioning-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: deploy cloudformation
          command: |
            set -x
            aws cloudformation deploy --template-file cloudformation/network_layer.yml --stack-name networklayer
            aws cloudformation deploy --template-file cloudformation/security_layer.yml --stack-name securitylayer --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation deploy --template-file cloudformation/application_layer.yml --stack-name applicationlayer --capabilities CAPABILITY_IAM
      
  execute-ansible-playbook:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:tEZSyjFZuMgjp5IzskmSJez4J9MIkBs6wHDS2VHU344"
      - ansible-playbook/install:
          version: 2.10.7
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-i ansible/inventory'

  execute-serverspec:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install:
          version: '3.2.3'
      - ruby/install-deps:
          app-dir: serverspec
      - run:
          name: 'execute-serverspec'
          command: |
            cd serverspec
            bundle exec rspec


workflows:
  version: 2
  provisioning-deploy:
    jobs:
      - provisioning-stack
      - execute-ansible-playbook:
          requires:
            - provisioning-stack
      - execute-serverspec:
          requires:
            - execute-ansible-playbook
