
- name: Install NVM
  become: true
  yum:
    name: "nvm"
    state: present

- name: Load NVM
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  args:
    warn: false

- name: Install Node.js
  shell: nvm install 17.9.1

- name: Install Yarn
  npm:
    name: yarn
    global: yes
    state: present

