
- name: Install nvm
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash"
  args:
    creates: ~/.nvm
  become: true

- name: Enable nvm
  shell: ". ~/.nvm/nvm.sh"
  args:
    executable: /bin/bash
  become: true

- name: Install Node.js
  shell: "nvm install 17.9.1"
  args:
    executable: /bin/bash
  become: true

- name: Install Yarn
  npm:
    name: yarn
    global: yes
    state: present

