
- name: Enable Amazon Linux Extras repository for Node.js
  yum:
    name: amazon-linux-extras
    state: present

- name: Install Node.js from Amazon Linux Extras
  yum:
    name: "nodejs14"
    state: present
  become: true
