- name: Remove Node.js
  become: true
  yum:
    name: nodejs
    state: absent
    autoremove: true

- name: Add Node.js repository
  become: true
  shell: curl -sL https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install Node.js
  become: true
  yum:
    name: nodejs
    state: present
