- name: Install curl
  yum:
    name: curl
    state: present

- name: Install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: ~/.nvm

- name: Load nvm
  shell: source ~/.bashrc
  environment:
    PATH: "{{ ansible_env.PATH }}"

- name: Install Node.js 17.9.1 version
  shell: |
    source ~/.bashrc
    nvm install 17.9.1
  args:
    executable: /bin/bash

- name: Install Yarn globally using npm
  npm:
    name: yarn
    global: yes
  environment:
    PATH: "/home/ec2-user/.nvm/versions/node/v20.12.0/bin:$PATH"




