- name: check if nodejs already installed
  stat:
    path: /usrbin/node
  register: nodejs_bin

- name: add repository for nodejs
  shell: bash -lc "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash"
  when: not nodejs_bin.stat.exists
  become: true

- name: install nodejs
  yum:
    name: nodejs
    state:  installed
  become: true
  when: not nodejs_bin.stat.exists

- name: install yarn
  npm:
    name: yarn
    state: present
    global: true
  become: true
  when: not nodejs_bin.stat.exists
