# Clone APP
- name: Check if the folder exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app
  register: folder_check

- name: Clone repository
  git:
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: /home/ec2-user/raisetech-live8-sample-app
  when: not folder_check.stat.exists
      
- name: Change directory
  shell: cd raisetech-live8-sample-app

- name: Install Bundler
  shell: bash -lc "bundle install"
  args:
    chdir: raisetech-live8-sample-app

# RDS
- name: Check if database.yml.sample exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/config/database.yml.sample
  register: file_check

- name: Rename database.yml.sample
  command: mv /home/ec2-user/raisetech-live8-sample-app/config/database.yml.sample /home/ec2-user/raisetech-live8-sample-app/config/database.yml
  when: file_check.stat.exists

- name: Render database.yml from template
  template:
    src: roles/setup_server/template/database.yml.j2
    dest: /home/ec2-user/raisetech-live8-sample-app/config/database.yml

# puma
- name: Check if puma.service.sample exists
  stat:
    path: /path/to/samples/puma.service.sample
  register: puma_service_check

- name: Move puma.service
  command: mv /home/ec2-user/raisetech-live8-sample-app/samples/puma.service.sample /home/ec2-user/raisetech-live8-sample-app/etc/systemd/system/puma.service
  when: puma_service_check.stat.exists

- name: Check if puma.rb exists
  stat:
    path: /home/ec2-user/raisetech-live8-sample-app/webpack/puma.rb
  register: puma_check

- name: Generate puma.rb from template
  template:
    src: roles/setup_server/template/puma.rb.j2  
    dest: /home/ec2-user/raisetech-live8-sample-app/config/puma.rb

- name: Start Puma service
  systemd:
    name: puma
    state: started

