
# mysqlのインストール

# MariaDBの削除
- name: Remove MariaDB
  become_user: root
  yum:
    name: mariadb-server
    state: absent

- name: Import GPG key 
  become_user: root
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

# 公開リポジトリを追加
- name: Install MySQL repository
  become_user: root
  yum:
    name: 'https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm'
    state: present

# mysql本体をインストール
- name: Install MySQL community server
  become_user: root
  yum:
    name: mysql-community-server
    state: present

- name: Start MySQL service
  become_user: root
  service:
    name: mysqld
    state: started
    enabled: yes