---
- name: remove the MariaDB
  become_user: root
  yum:
    name: mariadb-server
    state: absent

- name: Import MySQL GPG key
  become_user: root
  shell: rpm --import "https://repo.mysql.com/RPM-GPG-KEY-mysql-2022"
  args:
    creates: /var/lib/mysql/mysql80-community-release-el7-7.noarch.rpm

- name: install the mysql rpm from a remote repo
  become_user: root
  yum:
    name: 'https://dev.mysql.com/get/mysql80-community-release-el7-11.noarch.rpm'
    state: present

# - name: enable mysql57-community
#   become_user: root
#   shell: |
#     yum-config-manager --disable mysql80-community
#     yum-config-manager --enable mysql57-community

# - name: Import a key from a url
#   become_user: root
#   ansible.builtin.rpm_key:
#     state: present
#     key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

# - name: install mysql-community-server
#   become_user: root
#   yum: 
#     name: mysql-community-server
#     state: latest

# - name: install mysql-devel
#   become_user: root
#   yum: 
#     name: mysql-devel
#     state: latest