- name: install mysql
  yum:
    name:
      - mysql
      - mysql-devel
    state:  installed
  become: true

- name: create dir for rails-app
  file:
    path: "{{ app_root_dir }}"
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0775
  become: true
  when: not has_directory_srv.stat.exists

- name: clone rails-app
  git:
    repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git
    dest: "{{ app_root_dir }}"
  when: not was_cloned_rails.stat.exists