- name: Change permissions of /home/ec2-user
  become_user: root
  file:
    path: /home/ec2-user
    mode: 0701

- name: Install nginx
  become_user: root
  command: amazon-linux-extras install nginx1 -y

- name: Start nginx service
  become_user: root
  service:
    name: nginx
    state: started

- name: create app.conf
  become_user: root
  template:
    src: roles/nginx/template/nginx.conf.j2
    dest: "/etc/nginx/conf.d/app.conf"

- name: Enable nginx service
  become_user: root
  service:
    name: nginx
    enabled: yes