- name: Enable EPEL repository
  become_user: root
  command: amazon-linux-extras install epel -y

- name: Install Nginx
  become_user: root
  yum:
    name: nginx
    state: latest

- name: Start nginx service
  service:
    name: nginx
    state: started

- name: Enable nginx service
  service:
    name: nginx
    enabled: yes