- name: Change permissions of /home/ec2-user
  become_user: root
  file:
    path: /home/ec2-user
    mode: 0701

- name: Enable EPEL repository
  become_user: root
  command: amazon-linux-extras install epel -y

- name: Install Nginx
  become_user: root
  yum:
    name: nginx
    state: latest

- name: Start nginx service
  become_user: root
  service:
    name: nginx
    state: started

- name: create rails.conf
  become_user: root
  template:
    src: roles/nginx/template/nginx.conf.j2
    dest: "/etc/nginx/conf.d/app.conf"

- name: Enable nginx service
  become_user: root
  service:
    name: nginx
    enabled: yes