- name: yum update
  yum:
    name: '*'
    state: latest
  become: true

- name: install general packages
  yum:
    name: 
      - git 
      - bzip2 
      - readline-devel 
      - zlib-devel 
      - gcc 
      - libyaml-devel 
      - libffi-devel 
      - gdbm-devel 
      - ncurses-devel 
      - gcc-c++ 
      - mysql-devel 
      - ImageMagick 
      - ImageMagick-devel
      - glibc
    state: installed
  become: true