- hosts: 52.195.190.137
  
  vars: 
    home_dir: /home/ec2-user
    app_root_dir: /var/www/rails_app
    ruby_version: 3.2.3
    node_version: 17.9.1
    bundler_version: 2.3.14
    my_app_repo: https://github.com/yuta-ushijima/raisetech-live8-sample-app.git

  roles:
    - general
    # - node_yarn
    # - ruby
    # - rails
    - nginx
    # - setup_server